language: php

env:
  # - GLPI_SOURCE="https://github.com/flyve-mdm/glpi -b 9.1.2-backport" FUSION_SOURCE="https://github.com/fusioninventory/fusioninventory-for-glpi -b glpi9.1+1.1"
  - GLPI_SOURCE="https://github.com/glpi-project/glpi -b master" FUSION_SOURCE="https://github.com/fusioninventory/fusioninventory-for-glpi -b master"

before_script:
  - git clone --depth=1 $GLPI_SOURCE ../glpi && cd ../glpi
  - composer install --no-dev
  - sed -e "s/return extension_loaded('mcrypt');/return false;/" -i vendor/ircmaxell/random-lib/lib/RandomLib/AbstractMcryptMixer.php
  - php tools/cliinstall.php --db=glpi-test --user=travis --tests
  - mkdir plugins/fusioninventory && git clone --depth=1 $FUSION_SOURCE plugins/fusioninventory
  - mv ../flyve-mdm-glpi-plugin plugins/flyvemdm
  - cd plugins/flyvemdm && composer install -o

script:
  - vendor/bin/phpunit --verbose
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ *.php install/ inc/ front/ ajax/ tests/; fi

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: nightly
  allow_failures:
    - php: 7.1
    - php: nightly

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

