language: php


env:
  global:
    - GLPI_SOURCE="https://github.com/glpi-project/glpi" 
    - FI_SOURCE="https://github.com/fusioninventory/fusioninventory-for-glpi"
    - CS=7.2
    - secure: Y9sG3lZ3Fn3t5BXvcMJQxWsdSUVQgF4M08E6oouYrRc95HEj3ZwZOqp6Df58u8CQFA0EKJyvCBLn8UicvHGMKAD0RwGLBdSP4Ji9gJRZkyMZi79awSshdva/c8dqVQrRd4asuTNQfcagVJpNDnY8sYusw504JUilK3vFVp+39nNZUkcvT69NGVIlXzgHTYinBkVuqDhf5eVtcLcaESLEshrg+5ZERdm+0KifdJVREzhicJxofnmTl/wBsIP7XiQqspljf2/SxLqreGmWXYXUfqIwIOVtsd9fkZChQCz8USC7P427tH6styRDYuMCtvA9b/T/XacSdKFbuDezff3NbIM3b5BebDyCrOK5MGSOdRUY5RuyZN4R5LjePUE++9QNCUPeDSkfb23v0VfuqXIRAxfdtik517GzFy6O7/e6FU1msVZlGQED7Uek9nqnupj+0lIq+99Jcm1UCNJu1NTL2Tv80XXqySaxyE4Sedq/FiYAsy1bo2cg2367I2b4FhFXaJCKkFHcdjHXAeurkRy/brSPhBNoOO5/GA3RepUErgly4P8TLZqHNZv8rgMUoQ88sdwDyXG7dY4UwWiTlCkxMBTqBqJanlTMA9zn2bYyMDioTGnA7+VYAA8cddjFOMVrmmuFJ+YV2x1+5B5qd+Wt8RPwcPQDyqaiN5amb1HGeMA=
  matrix:
    - GLPI_BRANCH=9.2.1 FI_BRANCH=glpi9.2+1.0
    - GLPI_BRANCH=9.2/bugfixes FI_BRANCH=glpi9.2+1.0
    - GLPI_BRANCH=master FI_BRANCH=master

php: 
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

allow_failures:
  - php: nightly
      
before_script:
  - mysql -u root -e 'create database glpitest;'
  - rm -f composer.lock
  - tests/config-composer.sh
  - git clone --depth=1 $GLPI_SOURCE -b $GLPI_BRANCH ../glpi && cd ../glpi
  - composer install --no-dev --no-interaction
  - php tools/cliinstall.php --db=glpitest --user=root --tests
  - mkdir plugins/fusioninventory && git clone --depth=1 $FI_SOURCE -b $FI_BRANCH plugins/fusioninventory
  - IFS=/ read -a repo <<< $TRAVIS_REPO_SLUG
  - mv ../${repo[1]} plugins/flyvemdm
  - cd plugins/flyvemdm && composer install --no-interaction

script:
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install -ncc
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-unit --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI
  - for f in `ls tests/suite-integration/`; do vendor/bin/atoum -ft -bf tests/bootstrap.php --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI CommonDBRelation CommonDBConnexity ProfileRight -f tests/suite-integration/$f; done;
  - vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall --ncc
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ]] ; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ *.php install/ inc/ front/ ajax/ tests/; fi


cache:
  directories:
    - $HOME/.composer/cache
    
notifications:
  webhooks: https://hooks.aethonan.pro/travisci/-1001061475099/
