version: 2

shared: &shared
  steps:
    - checkout
    - run:
        name: CI level dependencies
        command: |
          sudo apt-get update
          sudo apt-get install -y mysql-client libpng-dev libxml2-dev
          sudo docker-php-ext-install mysqli gd xmlrpc zip
          sudo apt-get install -y mosquitto mosquitto-auth-plugin
    - run:
        name: M2M dependency
        command: |
          tests/before_install.sh
    - run:
        name: Dependencies
        command: |
          tests/before_script.sh
    - run:
        name: Installation tests
        command: |
          vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-install -ncc
    - run:
        name: Run MQTT daemon
        command: |
          #php scripts/mqtt.php --tests > /dev/null 2>&1 &
    - run:
        name: Unit tests
        command: |
          vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-unit --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI
    - run:
        name: Integration tests
        command: |
          vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-integration -mcn 1 --nccfc CommonTreeDropdown CommonDropdown CommonDBTM CommonGLPI
    - run:
        name: Uninstallation tests
        command: |
          vendor/bin/atoum -ft -bf tests/bootstrap.php -d tests/suite-uninstall --ncc
    - run:
        name: Coding standards
        command: |
          if [[ ${TRAVIS_PHP_VERSION:0:3} == "$CS" ]] && [ "$GLPI_BRANCH" = "9.2/bugfixes" ]; then vendor/bin/phpcs -p --standard=vendor/glpi-project/coding-standard/GlpiStandard/ *.php install/ inc/ front/ ajax/ tests/; fi

jobs:
  "php5.6":
    <<: *shared
    docker:
      - image: circleci/php:5.6-apache-node-browsers
      - image: circleci/mariadb:10.1
  "php7.0":
    <<: *shared
    docker:
      - image: circleci/php:7.0-apache-node-browsers
      - image: circleci/mariadb:10.1
  "php7.1":
    <<: *shared
    docker:
      - image: circleci/php:7.1-apache-node-browsers
      - image: circleci/mariadb:10.1
  "php7.2":
    <<: *shared
    docker:
      - image: circleci/php:7.2-apache-node-browsers
      - image: circleci/mariadb:10.1

workflows:
  version: 2
  tests_all:
    jobs:
      - php5.6
      - php7.0
      - php7.1
      - php7.2
